### ISSUE TITLE
public share with allowed upload and password protection: endlees loading loop

### ISSUE THREAD

**Issue by simarilius** [interfasys/galleryplus#55] opened 2016-07-17 19:13 UTC
I think this Bug is still in Gallery+
https://github.com/owncloud/core/issues/23066

had to switch back to the standard Gallery.

**Comment by ehsan7715** [comment] 2016-07-20 10:43
yes Gallery+ is the problem 
my server is okay after disabling gallery+ App

**Comment by marsdenpete** [comment] 2016-07-20 12:33
I'm having the same problem, have removed gallery + and the 5 second refresh was removed

**Comment by oparoz** [comment] 2016-07-20 12:45
This is a duplicate of https://github.com/interfasys/galleryplus/issues/51 which was fixed 3 weeks ago in master. I just need to release a new package, hopefully today.

**Closed by oparoz** 2016-07-20 12:45 UTC
